### ISSUE TITLE
Spring 16 causing tests to fail

### ISSUE THREAD

**Issue by rfjolnisson** [financialforcedev/fflib-apex-mocks#13]
fflib_ApexMocksTest class is currently failing on orgs that are running Spring '16.
As of 6 Feb 2016 EU5 has been updated and we are getting several failed asserts from the library. On EU0, EU1, EU2 and EU3, which have not yet been updated to newest release, the tests run smoothly.

As we are not using the mocks extensively, we plan to comment out the test class so we carry on with new release of our managed package.

TEST RESULTS:
-------------------------------
METHOD RESULT 
whenStubExceptionTheExceptionShouldBeThrown : Fail
STACK TRACE 
Class.KaptioTravel.fflib_ApexMocksTest.whenStubExceptionTheExceptionShouldBeThrown: line 222, column 1
MESSAGE 
System.AssertException: Assertion Failed

METHOD RESULT 
whenStubMultipleVoidMethodsWithExceptionsThenExceptionsShouldBeThrown : Fail
STACK TRACE 
Class.KaptioTravel.fflib_ApexMocksTest.whenStubMultipleVoidMethodsWithExceptionsThenExceptionsShouldBeThrown: line 268, column 1
MESSAGE 
System.AssertException: Assertion Failed: Stubbed exception should have been thrown.

METHOD RESULT 
whenStubVoidMethodWithExceptionAndCallMethodTwiceThenExceptionShouldBeThrownTwice : Fail
STACK TRACE 
Class.KaptioTravel.fflib_ApexMocksTest.whenStubVoidMethodWithExceptionAndCallMethodTwiceThenExceptionShouldBeThrownTwice: line 306, column 1
MESSAGE 
System.AssertException: Assertion Failed: Stubbed exception should have been thrown.

METHOD RESULT 
whenStubVoidMethodWithExceptionThenExceptionShouldBeThrown : Fail
STACK TRACE 
Class.KaptioTravel.fflib_ApexMocksTest.whenStubVoidMethodWithExceptionThenExceptionShouldBeThrown: line 242, column 1
MESSAGE 
System.AssertException: Assertion Failed: Stubbed exception should have been thrown.

**Comment by afawcett** [comment]
Thanks for raising this, @frup42 and I are looking into this....

**Comment by frup42** [comment]
Thanks for raising this issue (and fixing the similar issue in fflib-apex-common). We've tried running the failing test classes in a couple of different Spring 16 orgs, and have been unable to replicate the test failures. Hopefully this means the platform bug has been addressed!

Would you be able to confirm if these tests are still failing if you run them now? If they are, can you tell us your org details, in case they explain the difference in behaviour?
- What API version are using for the fflib classes?
- What API version for the rest of the classes, components?
- Which SF instance are you running on?
- What org type are you running (developer edition, professional edition etc)?
- Are you seeing the problem in more than one org? If so, are these all on Spring 16?

I wouldn’t want to ask you to share the login details for your orgs containing production code - so if you are getting the issue across other orgs, would you be able to give us a sanitised version without any of that private stuff in where you still get the issue?

Presumably this would be a case of deploying just apexmocks into an org, but like I say - when we’ve done this we have been unable to replicate.

**Comment by rfjolnisson** [comment]
Tests are now working on all our EU5 instances as normal.

We run everything on 33.0 at the moment. We were seeing this issue only on dev orgs on EU5 instances. We also have  EU0, EU1, EU2, EU3, AP0 & AP1 dev orgs where the tests ran as normal.

**Comment by afawcett** [comment]
Thanks for the update. :+1:

**Comment by dk-dev** [comment]
Just FYI, we are getting this too on NA5. Below is when deploying fflib-apex-common

fflib_ApexMocksTest
whenStubExceptionTheExceptionShouldBeThrown
System.AssertException: Assertion Failed 
Stack Trace: Class.fflib_ApexMocksTest.whenStubExceptionTheExceptionShouldBeThrown: line 222, column 1

fflib_ApexMocksTest	whenStubMultipleVoidMethodsWithExceptionsThenExceptionsShouldBeThrown	System.AssertException: Assertion Failed: Stubbed exception should have been thrown. 
		Stack Trace: Class.fflib_ApexMocksTest.whenStubMultipleVoidMethodsWithExceptionsThenExceptionsShouldBeThrown: line 268, column 1

fflib_ApexMocksTest	whenStubVoidMethodWithExceptionAndCallMethodTwiceThenExceptionShouldBeThrownTwice	System.AssertException: Assertion Failed: Stubbed exception should have been thrown. 
		Stack Trace: Class.fflib_ApexMocksTest.whenStubVoidMethodWithExceptionAndCallMethodTwiceThenExceptionShouldBeThrownTwice: line 306, column 1

fflib_ApexMocksTest	whenStubVoidMethodWithExceptionThenExceptionShouldBeThrown	System.AssertException: Assertion Failed: Stubbed exception should have been thrown. 
		Stack Trace: Class.fflib_ApexMocksTest.whenStubVoidMethodWithExceptionThenExceptionShouldBeThrown: line 242, column 1

fflib_SObjectUnitOfWorkTest	testDerivedUnitOfWork_CommitSuccess	System.DmlException: Insert failed. First exception on row 40; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Usage limit reached{Queries remaining:4}.........Stack{Class.rstk.ObjectFinder.checkUsage: line 191, column 1 Class.rstk.ObjectFinder.getCount: line 8, column 1 Class.rstk.ObjectFinder: line 14, column 1 Class.rstk.TriggerUtil.checkDuplicate: line 577, column 1 Class.rstk.TriggerHandler.checkDuplicate: line 207, column 1 Class.rstk.TriggerHandler.before: line 194, column 1 Class.rstk.TriggerHandler.delegate: line 83, column 1 Trigger.rstk.OpportunityLineItem: line 2, column 1}: [] 
		Stack Trace: Class.fflib_SObjectUnitOfWork.SimpleDML.dmlInsert: line 91, column 1 Class.fflib_SObjectUnitOfWork.commitWork: line 304, column 1 Class.fflib_SObjectUnitOfWorkTest.testDerivedUnitOfWork_CommitSuccess: line 206, column 1

fflib_SObjectUnitOfWorkTest	testUnitOfWorkNewDirtyDelete	System.DmlException: Insert failed. First exception on row 40; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Usage limit reached{Queries remaining:4}.........Stack{Class.rstk.ObjectFinder.checkUsage: line 191, column 1 Class.rstk.ObjectFinder.getCount: line 8, column 1 Class.rstk.ObjectFinder: line 14, column 1 Class.rstk.TriggerUtil.checkDuplicate: line 577, column 1 Class.rstk.TriggerHandler.checkDuplicate: line 207, column 1 Class.rstk.TriggerHandler.before: line 194, column 1 Class.rstk.TriggerHandler.delegate: line 83, column 1 Trigger.rstk.OpportunityLineItem: line 2, column 1}: [] 
		Stack Trace: Class.fflib_SObjectUnitOfWork.SimpleDML.dmlInsert: line 91, column 1 Class.fflib_SObjectUnitOfWork.commitWork: line 304, column 1 Class.fflib_SObjectUnitOfWorkTest.testUnitOfWorkNewDirtyDelete: line 69, column 1

**Comment by afawcett** [comment]
Salesforce are working on a fix for this.

**Comment by Oblongmana** [comment]
Just dropping in to give a +1 on NA3. Will comment out in the interim

**Comment by loganm** [comment]
+ 1 on CS6

Problem is transient. Deploy again and the tests will pass.
Good to hear Salesforce is on the case.
