### ISSUE TITLE
Add support for subquery results

### ISSUE THREAD

**Issue by jondavis9898** [financialforcedev/fflib-apex-mocks#18]
Came across a need to generate subquery data today and came across this gem by Andrew from 2014 - http://andyinthecloud.com/2014/12/03/mocking-soql-sub-select-query-results/.

Not sure if the proper home for something like this is Apex Mocks or the upcoming test builder repo?  I can see merit in both places.  Thoughts?

**Comment by frup42** [comment]
You're right, I think it would be right at home in both repos. We have in fact brought it into ApexMocks in our internal repo, so it would be great to keep parity between the two as far as possible. I'll bring it across now.

**Comment by jondavis9898** [comment]
Great addition, thank you! :+1:
