### ISSUE TITLE
Matchers not cleared when verifying method was not called

### ISSUE THREAD

**Issue by jondavis9898** [financialforcedev/fflib-apex-mocks#19]
I'll write a test for this as soon as I can but believe there is an issue in fflib_MethodCountRecorder::getMethodCount.

If a method is verified to not have been called (e.g. verify(myMock, 0)) and the method was not called (as expected), the matchers are not being cleared.  Therefore, on the next verify, the following exception occurs:

    fflib_ApexMocks.ApexMocksException: The number of matchers defined (6). does not match the number expected (3)
    If you are using matchers all arguments must be passed in as matchers.
    For example myList.add(fflib_Match.anyInteger(), 'String') should be defined as myList.add(fflib_Match.anyInteger(), fflib_Match.eq('String')).

I haven't had time to dig in to how the new matcher logic behaves but it appears that adding an "else if" to clear the matchers resolves the issue - not sure it's the correct solution though.  Apologize for not having a test for this, will write one as soon as I can.

    if (methodCountByArgs != null)
    {
        if (fflib_Match.Matching)
        {
            List<fflib_IMatcher> matchers = fflib_Match.getAndClearMatchers(methodArg.argValues.size());
            
            for (fflib_MethodArgValues args : methodCountByArgs.keySet())
            {
                if (fflib_Match.matchesAllArgs(args, matchers))
                {
                    retval += methodCountByArgs.get(args);
                }
            }
        }
        else
        {
            if (methodCountByArgs.get(methodArg) != null)
            {
                return methodCountByArgs.get(methodArg);
            }
        }
    } else if (fflib_Match.Matching) {
        fflib_Match.getAndClearMatchers(methodArg.argValues.size());
    }

Thoughts?

**Comment by frup42** [comment]
Good morning, thanks for spotting and reporting. I've created a pull request with the fix and added a unit test to verify the behaviour.

Everything worked fine when verifying that method X was called with args Y, as long as method X was called with args Z.
If method X was never called with any arguments, you'd get the behaviour you encountered.

**Comment by jondavis9898** [comment]
:+1: Thank you!
