### ISSUE TITLE
fflib_MatcherDefinitionsTest.whenIsBlankWithMatchesShouldReturnCorrectResults() fails

### ISSUE THREAD

**Issue by jakejuby** [financialforcedev/fflib-apex-mocks#33]
fflib_MatcherDefinitionsTest.whenIsBlankWithMatchesShouldReturnCorrectResults() has an assertion around matching a null parameter. It fails for me.

**Comment by XoNoX79** [comment]
To me that test runs successfully, however if I comment it out the "arg == null ||"  check in the matches method of the StringIsBlank class of the fflib_MatcherDefinitions, it fails for that assertion you mentioned. I've runned against the master branch. Do you have that "arg == null ||"  in your version?

**Comment by jakejuby** [comment]
this is my StringIsBlank class
```
/**
 * StringIsBlank matcher: checks if the supplied argument is a blank String
 */
public class StringIsBlank implements fflib_IMatcher
{
    public Boolean matches(Object arg)
    {
        return arg instanceof String ? String.isBlank((String)arg) : false;
    }
}
```

**Comment by jakejuby** [comment]
I'm using the code from the feature/stub-api branch

**Comment by XoNoX79** [comment]
return (arg == null || arg instanceof String) ? String.isBlank((String)arg) : false;

would solve your issue.

**Comment by jakejuby** [comment]
That is what it is in master, so it does fix it. In feature/stub-api it looks like the snippet posted above, but it doesn't show up in the diff of #28

**Comment by XoNoX79** [comment]
https://github.com/financialforcedev/fflib-apex-mocks/commit/3fa5f061a3fe1ebad2b815b78ee374b1ed75e9c2

I would say because #28 has been created before #27 get merged but then master hasn't been merged in #28, so the diff is against the master verision from witch #28 has been taken.

**Comment by frup42** [comment]
This is a [documented](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_keywords_instanceof.htm) behaviour change when going from API v31 and earlier to v32 and later.
In Apex saved with API version 32.0 and later, instanceof returns false if the left operand is a null object.
PR #36 should fix this regardless of the API version used in fflib_MatcherDefinitions.

**Comment by frup42** [comment]
Merged PR, fixing this.
