### ISSUE TITLE
apex-mocks-generator skips the line after the interface definition

### ISSUE THREAD

**Issue by adtennant** [financialforcedev/fflib-apex-mocks#4]
The title explains it all really, but here are some examples which show how this actually affects things in practice (note the positions of the curly braces):

```
public interface MyInterface
{
     void foo();
     void bar();
}
```

Generates:
```
public class MockMyInterface implements MyInterface
{
	private fflib_ApexMocks mocks;

	public MockMyInterface(fflib_ApexMocks mocks)
	{
		this.mocks = mocks;
	}

	public void foo()
	{
		mocks.mockVoidMethod(this, 'foo', new List<Object> {});
	}

	public void bar()
	{
		mocks.mockVoidMethod(this, 'bar', new List<Object> {});
	}
}
```

This is correct.

---

```
public interface MyInterface {

     void foo();
     void bar();
}
```

Generates:
```
public class MockMyInterface implements MyInterface
{
	private fflib_ApexMocks mocks;

	public MockMyInterface(fflib_ApexMocks mocks)
	{
		this.mocks = mocks;
	}

	public void foo()
	{
		mocks.mockVoidMethod(this, 'foo', new List<Object> {});
	}

	public void bar()
	{
		mocks.mockVoidMethod(this, 'bar', new List<Object> {});
	}
}
```

This is also correct.

---

However, as soon as I remove that blank line after the method definition:

```
public interface MyInterface {
     void foo();
     void bar();
}
```

Generates:
```
public class MockMyInterface implements MyInterface
{
	private fflib_ApexMocks mocks;

	public MockMyInterface(fflib_ApexMocks mocks)
	{
		this.mocks = mocks;
	}

	public void bar()
	{
		mocks.mockVoidMethod(this, 'bar', new List<Object> {});
	}
}
```

This is not correct. Notice that `foo()` has gone missing.

**Comment by briansieb** [comment]
I have also noticed this issue.  Any chance of open sourcing the mock test generator jar? :)

**Comment by afawcett** [comment]
Yes, i don't see a problem with that, @comic96 would this go in this repo or another?

**Comment by comic96** [comment]
I've been wondering about that, I think probably in a separate repo.

**Comment by comic96** [comment]
Hi Andy,


before sharing the mock generator, I wanted to make sure there are at least some basic unit tests in place. Unusually for me I didn�t write tests, because the generator started out almost as an after thought, took on a life of it�s own, and I never had
 time to go back and write unit tests.


However before sharing with the world at large I think we probably should! I imagine it would only take me 1 day to put something in place, I�ll see if I can get the time to do that.


Thanks
Paul

**Comment by comic96** [comment]
Will work on fixing this as soon as possible!

**Comment by adtennant** [comment]
Awesome. Guess I can just fix this myself in that case then :)

**Comment by JohnDTheMaven** [comment]
@comic96 - This is probably the same issue that I mentioned to you last month.  Let me know if I can help.

**Comment by briansieb** [comment]
Thanks Andy and Paul!

**Comment by comic96** [comment]
apex-mocks-generator 3.1.2 released to resolve this issue

**Comment by john-storey** [comment]
Was the generator made available as an open-source project?

> briansieb commented on Mar 16, 2015
> I have also noticed this issue. Any chance of open sourcing the mock test generator jar? :)
