### ISSUE TITLE
Mock static methods not supported

### ISSUE THREAD

**Issue by Nagendra080389** [financialforcedev/fflib-apex-mocks#41]
I dont think static method mocking is supported currently.
Java Mockito has a method to mock static methods like PowerMock.mockStatic(), but couldn't find a way to mock my static methods in a non static class?

**Comment by cropredy** [comment]
N.B. [Apex Stub Api](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_testing_stub_api.htm) as of V40.0 does not support stubbing static methods

**Comment by frup42** [comment]
Static methods are hard to mock in Java and currently impossible to mock in Apex, so I'm going to close this as we can't really do anything with it.

For the sake of argument, let's assume you are using the Stub API. The Stub API returns mocks that *extend* real objects, but *override* all inherited methods to delegate invocation handling to the stub provider.

Static methods don't belong to any instance of a class, and so can't be overridden. [Here's](https://stackoverflow.com/questions/2223386/why-doesnt-java-allow-overriding-of-static-methods) a good discussion as to why you can't override static methods - it's talking about Java but the concept extends to Apex.

PowerMock allows static method mocking through it's test runner, which can modify class loading and introspect in ways that are way beyond the scope of Apex.

You can however workaround this by wrapping unmockable methods with mockable ones. This works for static methods, or platform methods, or those in other namespaces.
e.g. `Database.setSavepoint(..)` can be wrapped in a method...

    public class Wrapper {
        public Savepoint setSavepoint() {
            return Database.setSavepoint();
        }
    }
