### ISSUE TITLE
thenReturn(null) not supported?

### ISSUE THREAD

**Issue by gcobr** [financialforcedev/fflib-apex-mocks#5]
I noticed that if I try to program my mock to return a null value, like
```
when(theMock.someMethod('someValue')).thenReturn(null)
```

I get a 
System.NullPointerException: Attempt to de-reference a null object Class.fflib_ApexMocks.mockNonVoidMethod: line 246, column 1

**Comment by afawcett** [comment]
Thanks for raising this.

FYI @comic96

**Comment by afawcett** [comment]
Also feel free if you can see a fix to raise a PR, myself and @comic96 will review.

**Comment by frup42** [comment]
Is this still an issue? I can't replicate so I'm going to close. If you can provide replication steps, I'm happy to reopen.

I'm a bit confused by the stack trace claiming the null pointer is on line 246. There are only 2 commits for fflib_ApexMocks.cls. The first commit doesn't have 246 lines in it, and I was unable to replicate the issue with the second commit.
