### ISSUE TITLE
Simulate Mockito.spy behavior?

### ISSUE THREAD

**Issue by dudunato** [financialforcedev/fflib-apex-mocks#63]
Hi Guys,

I was wondering if there's a way of testing the following scenario:

``` apex
class A {

  void go() {
      Obj o1 = do1();
      Obj2 o2 =  do2(o1);
      do3(o2);
  }

  public Obj do1() {
    // a lot of complexity in here
  }

  public Obj2 do2() {
    // a lot of complexity in here
  }

  public void do3() {
    // a lot of complexity in here
  }
}
```

Then I would like to be able to mock do1, do2 and do3 when I'm testing against go(), and of course, I'll have separated tests for do1, do2 and do3.

With mockito I could achieve this by:

``` apex
A a = Mockito.spy(new A());
// stubs and so on..
a.go();
verify(a, times(1)).do1();
```

I've tried to look at the implementation but I didn't have any insight. Thanks guys!

**Comment by dudunato** [comment]
@dfruddffdc any insight on this one?

**Comment by dfruddffdc** [comment]
Hi, I see you've also discussed this on Twitter with @afawcett . For posterity, I'll put the link to your tweet [here](https://twitter.com/dudunato/status/965608397377867776).

Spying would be really useful, especially where integrating with third party code or across namespaces, where you don't really want to mock the behaviour. But unfortunately, I can't see any way to achieve this on Salesforce.

fflib_ApexMocks doesn't have the reflective capability to invoke a method by name, the Stub needs to decide up-front whether it's going to invoke the real method or a stub. I wouldn't want to attempt this in the ApexMocks generator, which currently (very deliberately) generates very lean classes which delegate all mocking logic to fflib_ApexMocks. It would have to perform the real function but still register the method invocation for verifications.

I think in reality, this can only come from an enhancement to the Stub API. As such, closing this issue.

**Comment by afawcett** [comment]
@dudunato i have taken note of this as a use case to enhance the Stub API, no timescales as yet though.

**Comment by cropredyHelix** [comment]
I have a related use case which is perfectly described by [this stackoverflow question](https://stackoverflow.com/questions/24896636/how-to-verify-invocation-of-super-method-of-parent-class) - mocking a method in the super class.

Does @dfruddffdc answer from 2018-02-21 still apply when the method to be mocked is from a super class? Is there a workaround?
