### ISSUE TITLE
Method not recorded for void method that throws exception

### ISSUE THREAD

**Issue by jondavis9898** [financialforcedev/fflib-apex-mocks#9]
When mocking a Void method that throws an exception, it appears that the method will not be recorded since the exception is thrown before recording the method call.

Should line 214 move to line 207?
https://github.com/financialforcedev/fflib-apex-mocks/blob/master/src/classes/fflib_ApexMocks.cls#L214

**Comment by afawcett** [comment]
@frup42 thoughts?

**Comment by frup42** [comment]
It certainly should https://github.com/financialforcedev/fflib-apex-mocks/pull/12

**Comment by jondavis9898** [comment]
Thank you!
